name = 'lanjmp'
main = "worker.js"
compatibility_date = "2024-11-11"
# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "nas-link"
id = "d5f4221fa4474ff983538d3e2f806fc5"

